#!/bin/sh
# Fail fast and avoid accidental globbing / word splitting issues.
set -eu

VSCODE_GIT_GRAPH_ASKPASS_PIPE=$(mktemp)
VSCODE_GIT_GRAPH_ASKPASS_PIPE="$VSCODE_GIT_GRAPH_ASKPASS_PIPE" "$VSCODE_GIT_GRAPH_ASKPASS_NODE" "$VSCODE_GIT_GRAPH_ASKPASS_MAIN" "$@"
cat "$VSCODE_GIT_GRAPH_ASKPASS_PIPE"
rm "$VSCODE_GIT_GRAPH_ASKPASS_PIPE"